In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report

In [3]:
data = pd.read_csv(r"D:\ML\soil_measures.csv")
data

        N   P   K        ph    crop
0      90  42  43  6.502985    rice
1      85  58  41  7.038096    rice
2      60  55  44  7.840207    rice
3      74  35  40  6.980401    rice
4      78  42  42  7.628473    rice
...   ...  ..  ..       ...     ...
2195  107  34  32  6.780064  coffee
2196   99  15  27  6.086922  coffee
2197  118  33  30  6.362608  coffee
2198  117  32  34  6.758793  coffee
2199  104  18  30  6.779833  coffee

[2200 rows x 5 columns]

In [4]:
le = LabelEncoder()
data['crop'] = le.fit_transform(data['crop'])
data['crop']

0       20
1       20
2       20
3       20
4       20
        ..
2195     5
2196     5
2197     5
2198     5
2199     5
Name: crop, Length: 2200, dtype: int32

In [5]:
X = data.iloc[:,:-1]
X

        N   P   K        ph
0      90  42  43  6.502985
1      85  58  41  7.038096
2      60  55  44  7.840207
3      74  35  40  6.980401
4      78  42  42  7.628473
...   ...  ..  ..       ...
2195  107  34  32  6.780064
2196   99  15  27  6.086922
2197  118  33  30  6.362608
2198  117  32  34  6.758793
2199  104  18  30  6.779833

[2200 rows x 4 columns]

In [6]:

Y = data['crop']
Y

0       20
1       20
2       20
3       20
4       20
        ..
2195     5
2196     5
2197     5
2198     5
2199     5
Name: crop, Length: 2200, dtype: int32

In [12]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [13]:
model = RandomForestClassifier(n_estimators=10)
model.fit(X_train,Y_train)
model

RandomForestClassifier(n_estimators=10)

In [9]:
y_pred = model.predict(X_test)
y_pred

array([21, 21, 17, 17,  0, 12,  7, 13, 14, 10,  2, 12, 19,  5,  4, 19,  7,
       11, 17, 15,  5, 17, 16, 17,  3, 20, 14, 16, 18, 20, 19, 14,  8,  9,
        8, 10,  8,  3,  3,  9, 17,  4, 10, 11, 14, 11, 10,  4, 21, 11,  2,
        5,  7, 14,  5,  9,  6,  0,  1, 10, 21,  4, 10, 16, 17,  9, 16, 20,
       21, 14, 15,  4,  8,  1,  2, 17,  1,  6, 21, 16,  5,  3,  8, 13, 16,
       12,  5, 13,  2, 19, 11, 13,  6, 17, 14, 13,  9,  5, 10, 18,  4, 20,
       16, 15, 21,  9, 21,  1, 18, 13,  1,  8,  6, 19, 18,  3, 11,  4, 19,
        8, 10,  7, 18,  4,  3,  2,  4, 11,  1, 10,  1, 18, 19,  3, 12, 16,
       18,  1,  1,  0,  9, 15, 14,  2,  4, 11,  0,  4,  9, 13, 14, 10, 15,
       14, 13,  9, 18,  9, 11,  8,  3,  0, 16,  6, 20,  4,  7, 10, 21,  0,
        0,  2, 19,  3,  4, 11, 18,  0, 15,  8,  5,  5,  9,  8, 13,  9,  1,
        9,  4, 17, 17, 14, 12,  4, 15,  9, 11,  0, 10,  3,  7,  7,  1,  6,
       20, 19, 14,  1,  8, 14, 11,  3,  3,  3,  0,  8, 18, 17,  5,  2,  9,
       12, 12, 12, 17,  7,  3, 19,  3, 21,  0, 21, 21, 13, 12,  6,  4, 19,
        8, 15,  6, 17, 13, 11, 12, 15, 18, 14,  5,  0,  4,  6,  2,  8,  7,
       19,  5,  3,  6,  5, 12,  1, 17,  0,  3, 20, 18, 13, 14, 20, 19,  0,
       13, 20,  6,  4, 11,  3,  1,  8,  4,  5, 14, 21,  0,  1,  9,  2, 16,
        3, 15,  1,  0,  3,  5, 18, 16,  0,  4, 17, 15, 13, 17,  3, 19,  3,
       17, 10,  0, 19,  3, 12,  3, 19, 21, 18, 14, 21, 21,  9, 21, 12, 20,
        2,  3,  1, 18, 10, 17, 10, 14,  4,  6,  7,  0, 10,  1,  8,  7, 19,
        0, 14, 15,  5,  5, 18, 20,  9,  1, 11, 20, 11,  9, 12,  9,  4, 15,
        2, 11, 20, 13, 13, 12,  6, 17, 13,  6, 14, 16,  8,  2, 14,  5,  1,
       13, 17,  0, 19, 11,  4, 19,  0,  2,  8, 13, 10,  4,  2,  8, 14,  6,
       21,  7,  7,  4,  7, 21, 20, 12, 12,  5, 19,  1,  7,  8, 16,  6,  4,
       17, 15, 13,  8,  3, 13, 19, 21, 13,  6, 17, 15, 10,  8,  4, 13, 13,
       11, 20, 11,  4, 16, 19,  9, 21, 10,  2, 20,  8,  6,  6, 10])

In [10]:
ac = accuracy_score(Y_test,y_pred)
ac

0.7954545454545454

In [11]:
print(classification_report(Y_test, y_pred))

              precision    recall  f1-score   support

           0       0.77      0.74      0.76        23
           1       1.00      1.00      1.00        21
           2       0.81      0.65      0.72        20
           3       1.00      1.00      1.00        26
           4       0.82      0.85      0.84        27
           5       0.84      0.94      0.89        17
           6       0.89      1.00      0.94        17
           7       0.60      0.64      0.62        14
           8       0.65      0.65      0.65        23
           9       0.76      0.80      0.78        20
          10       0.35      0.64      0.45        11
          11       1.00      0.95      0.98        21
          12       0.82      0.74      0.78        19
          13       0.83      0.83      0.83        24
          14       0.82      0.95      0.88        19
          15       0.53      0.47      0.50        17
          16       1.00      1.00      1.00        14
          17       1.00      1.00      1.00        23
          18       0.56      0.39      0.46        23
          19       0.95      0.91      0.93        23
          20       0.69      0.58      0.63        19
          21       0.57      0.63      0.60        19

    accuracy                           0.80       440
   macro avg       0.79      0.79      0.78       440
weighted avg       0.80      0.80      0.79       440